# model
keep_lp: False

# solver
solver: 'gurobi'
solver_options:
  gurobi:
    Threads: 0
    Method: 2
    BarHomogeneous: 1
    Crossover: 1
    BarConvTol: 1e-8
  cplex:
    threads: 0
    lpmethod: 1
    solutiontype: 2
    barrier convergetol: 1e-8

  cbc: 0

# Time
# Start time and end time for slicing the database.
time:
  slice: ['2018-01-01T00:00', '2018-12-31T23:00']
  resolution: 1

# Space
region: "EU"

# RES
res:
  include: False
  # Give which technology should be installed using each strategy
  strategies:
    from_files: []
    no_siting: []
    siting: []
    bus: ['wind_offshore', 'pv_utility', 'pv_residential', 'wind_onshore']

  # For strategy = siting or no siting
  # Various data layers to be taken into account in potential site selection.
  spatial_resolution: 0.5
  timeslice: ['2018-01-01T00:00', '2018-01-01T23:00']
  use_ex_cap: True
  limit_max_cap: True

  # For strategy = siting
  modelling: 'pyomo' # Choice of modelling language. Available: 'gurobipy', 'docplex' and 'pyomo'
  solver: 'gurobi' # Choice of solver. Available: 'gurobi', 'cplex' and 'cbc'
  solver_options:
    gurobi:
      Threads: 0
      Method: 1
    cplex:
      solutiontype: 1
    cbc: 0
  write_lp: False
  write_log: False
  # Type of problem to be solved. Check resite.py for a full list.
  formulation: 'meet_RES_targets_agg' # 'meet_RES_targets_hourly' # 'meet_demand_with_capacity' #
  formulation_params: [0.1] # [0.5, 0.5, 0.5, 0.5]
  # Keeping files at the end of the run.
  keep_files: True

# Conventional generation
dispatch:
  include: True
  tech: "ccgt"

# Nuclear
nuclear:
  include: True
  use_ex_cap: True # Whether to include existing cap
  extendable: False

# Battery
battery:
  include: True
  type: "Li-ion"

# Hydro
phs:
  include: True
  use_ex_cap: True
  extendable: False
  cyclic_sof: True

ror:
  include: True
  use_ex_cap: True
  extendable: False

sto:
  include: True
  use_ex_cap: True
  extendable: False
  cyclic_sof: True

functionalities:
  snsp:
    include: False
    share: 0.65
  curtailment:
    include: False
    strategy: ['economic', 10.] # ['technical', 0.], ['technical', 1.], ['economic', 0.], ['economic', 9999.]
  load_shed:
    include: False
  import_limit:
    include: False
    share: 0.5
  co2_emissions:
    include: True
    strategy: 'global' # country, global
    reference_year: 1990 # Flat reference across all countries for now.
    mitigation_factor: 0.9

non_eu:
  res:
    NA: ["pv_utility_noneu"]
    GL: ["wind_onshore_noneu"]
    IS: ["wind_onshore_noneu"]
